# Generated by Django 3.1.6 on 2022-07-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
